Trip_jQuery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings_common, settings_dev


urlpatterns = [
    path('admin/', admin.site.urls),
    path('make_trip/', include('make_trip.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings_common.MEDIA_URL,
                    document_root=settings_dev.MEDIA_ROOT)

make_trip/urls.py
from django.urls import path
from . import  views

app_name = 'make_trip'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('trip/<int:num>', views.trip, name="trip"),
    path('members/<int:num>', views.members, name="members"),
    path('myPage', views.myPage, name="myPage"),
    path('groups', views.groups, name="groups"),
    path('group_trip/<int:num>', views.group_trip, name="group_trip"),
    path('delete/<int:num>', views.delete, name="delete"),
    path('other/<int:num>', views.other, name="other"),
    path('create_trip', views.create_trip, name="create_trip"),
    path('create_this_group_trip/<int:num>', views.create_this_group_trip, name="create_this_group_trip"),
    path('first_spot', views.first_spot, name="first_spot"),
    path('group_trip_first_spot/<int:num>', views.group_trip_first_spot, name="group_trip_first_spot"),
    path('trip_edit/<int:num>', views.trip_edit, name="trip_edit"),
    path('spot_edit/<int:num>', views.spot_edit, name="spot_edit"),
    path('transport_edit/<int:num>', views.transport_edit, name="transport_edit"),
    path('other_edit/<int:num>', views.other_edit, name="other_edit"),
    path('spot_delete/<int:num>', views.spot_delete, name="spot_delete"),
    path('other_delete/<int:num>', views.other_delete, name="other_delete"),
    path('group_remove/<int:num>', views.group_remove, name="group_remove"),
    path('member_delete/<int:num>', views.member_delete, name="member_delete"),
    path('tranSpot/<int:num>', views.tranSpot, name="tranSpot"),
    path('add_member/<int:num>', views.add_member, name="add_member"),
    path('add_member_complete/<token>', views.add_member_complete, name="add_member_complete"),
    path('add_group', views.add_group, name="add_group"),
    path('logout', views.LogoutView.as_view(), name="logout"),
]

make_trip/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.core.validators import MinLengthValidator, MinValueValidator
from django.utils import timezone
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _
from accounts.models import CustomUser


# Create your models here.
class Group(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='trip_user')
    title = models.CharField(max_length=30)

    def __str__(self):
        return '<' + self.title + '(' + str(self.user) + ')>'

class Member(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='member_user')
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='member_group')

    def __str__(self):
        return str(self.user) + ' (group:" ' + str(self.group) + ' " )'

class Trip(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='trip_group')
    trip_name = models.CharField(max_length=30)
    start = models.DateField()
    end = models.DateField()

    def __str__(self):
        return str(self.trip_name) + ' (' + str(self.group) + ',' + str(self.start)  + '〜' + str(self.end) + ')'

class Spot(models.Model):
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE, related_name='spot')
    spot_name = models.CharField(max_length=50)
    spot_time = models.DateTimeField()
    spot_cost = models.IntegerField(validators=[MinValueValidator(0, '0以上で入力してください')])

    def __str__(self):
        return str(self.spot_name) + ' (' + str(self.spot_time) + '+' + str(self.spot_cost) + ')'

class Other(models.Model):
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE, related_name='extra')
    extra_name = models.CharField(max_length=50)
    extra_cost = models.IntegerField(validators=[MinValueValidator(0, '0以上で入力してください')])

    def __str__(self):
        return str(self.extra_name) + ' (' + str(self.extra_cost) + ')'

class Transport(models.Model):
    spot = models.ForeignKey(Spot, on_delete=models.CASCADE, related_name='transport_spot')
    transport_name = models.CharField(max_length=30)
    transport_fee = models.IntegerField(validators=[MinValueValidator(0, '0以上で入力してください')])
    transport_time = models.DateTimeField()

    def __str__(self):
        return str(self.transport_name) + ': ' + str(self.transport_time) + ' (' + str(self.transport_fee) + ')'

class Budget(models.Model):
    predict_money = models.IntegerField(validators=[MinValueValidator(0, '0以上で入力してください')])
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE, related_name='budget')

    def __str__(self):
        return str(self.predict_money)

class Memo(models.Model):
    memo = models.TextField(blank=True, null=True)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE, related_name='trip_memo')

    def __str__(self):
        return str(self.memo)

'''
class Cost(models.Model):
    cost_name = models.CharField(max_length=30)
    cost_money = models.IntegerField(validators=[MinValueValidator(0, '0以上で入力してください')])
    spot = models.ForeignKey(Spot, on_delete=models.CASCADE, related_name='spot_cost')

    def __str__(self):
        return str(self.cost_name) + '(' + str(self.cost_money) + ')'
'''

make_trip/views.py
from django.http import HttpResponse, HttpResponseServerError
from django.http.response import HttpResponseBadRequest, Http404
from django.shortcuts import render, redirect
from .forms import BudgetForm, MemoForm, SignUp, Login, GroupForm, TripForm, SpotForm, OtherForm, TransportForm, AddGroup
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, login, authenticate
from .models import Budget, Spot, Other, Transport, Trip, Member, Group, Memo
from accounts.models import CustomUser
from django.db.models import Sum
import datetime
from django import forms
from django.utils.dateparse import parse_datetime
from django.views import generic
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import dumps, BadSignature, SignatureExpired, loads
from django.template.loader import render_to_string
from django.conf import settings
from django.utils.timezone import localtime
from django.contrib import messages
from django.views.decorators.csrf import requires_csrf_token
import requests
import json
import traceback


class IndexView(generic.TemplateView):
    template_name = 'make_trip/index.html'

class LogoutView(generic.TemplateView):
    template_name = 'make_trip/logout.html'

# @login_required(login_url='/make_trip/')
def add_member(request, num):
    try:
        this_group = Group.objects.get(id=num)
    except Group.DoesNotExist:
        raise Http404('このグループは存在しません')
    group = Group.objects.filter(id=num).values('title')[0]['title']

    # request.userがグループのメンバーかどうかを判定
    member_exist = Member.objects.filter(group=num).filter(user=request.user)

    if member_exist:
        current_site = get_current_site(request)   # requestしたサイトのurlの情報を返してくれる
        domain = current_site.domain    # requestしたサイトのdomain情報を返す

        params = {
            'protocol': request.scheme,    # schemeでrequestしたサイトのprotocolの情報を教えてくれる(大抵httpかhttps)
            'domain': domain,
            'token': dumps(this_group.pk),    # groupのidを暗号化してくれる
            'group': group,
        }

        return render(request, 'make_trip/add_member.html', params)

    else:
        return redirect(to='/make_trip/myPage')

# @login_required(login_url='/make_trip/')
def add_group(request):
    if request.method == 'POST':
        input_url = AddGroup(request.POST)
        print('input_url:', request.POST['input_url'])
        return redirect(to=request.POST['input_url'])
    else:
        input_url = AddGroup()

    params = {
        'input_url': input_url
    }

    return render(request, 'make_trip/add_group.html', params)

# @login_required(login_url='/make_trip/')
def add_member_complete(request, token):
    # 参加させるグループを取得
    try:
        id = loads(token)
        this_group = Group.objects.get(id=id)
    except Group.DoesNotExist:
        raise Http404('このグループは存在しません')
    group = Group.objects.filter(id=id).values('title')[0]['title']

    # グループに所属しているメンバーを取得する
    group_member = Member.objects.filter(group=this_group).values('user')
    member_email = [CustomUser.objects.filter(id=group_member[i]['user']).values('email')[0]['email'] for i in range(len(group_member))]

    if request.method == 'POST':
        if str(request.user) in member_email:   # request.userをstr型にしておく必要がある
            messages.info(request, 'すでにメンバーになっています。')
        else:
            member = Member()
            member.user = request.user
            member.group = this_group
            member.save()
            return redirect(to='/make_trip/myPage')
        # login(request, request.user, backend='django.contrib.auth.backends.ModelBackend')

    params = {
        'group': group,
        'token': token,
    }

    return render(request, 'make_trip/add_member_complete.html', params)


# マイページの部分の処理
# @login_required(login_url='/make_trip/')
def myPage(request):
    # requestしたユーザーがメンバーとして所属しているグループを取得
    group_member = Member.objects.filter(user=request.user).all().values('group')
    print('group_member:', group_member)

    # 所属しているグループのtrip情報を取得
    groups = Group.objects.filter(id__in=group_member)
    print('groups:', groups)

    # tripの情報があるかチェックする
    # group_exist = Group.objects.filter(user=request.user).count()

    # 次の旅行とこれまでの旅行をまとめるためのリストを作成しておく
    trip_content_before = []
    trip_content_future = []

    # DBにTripの情報が登録されている場合はそのデータを表示する
    if groups:
        trip_content = Trip.objects.all().filter(group__in=groups).values('id', 'trip_name', 'start', 'end')
        trip = Trip.objects.all().filter(group__in=groups)

        # 未来の旅行と過去の旅行に分ける
        for i in range(len(trip_content)):
            # tripがspotを持っていない場合はcontinueする
            spot_exist = Spot.objects.filter(trip=trip_content[i]['id'])
            if spot_exist:
                print('end:', trip_content[i]['end'])
                print('today:', datetime.date.today())
                if trip_content[i]['end'] < datetime.date.today():
                    # 過去の旅行の場合はtrip_content_beforeに格納する
                    trip_content_before.append(trip_content[i])
                else:
                    # 未来の旅行の場合はtrip_content_futureに格納する
                    trip_content_future.append(trip_content[i])
            else:
                # first_spotが登録されていないtripは削除する
                trip[i].delete()

    params = {
        'trip_content_future': trip_content_future,
        'trip_content_before': trip_content_before
    }

    return render(request, 'make_trip/mypage.html', params)

# @login_required(login_url='/make_trip/')
def groups(request):
    my_member = Member.objects.filter(user=request.user).values('group')

    # requestしたユーザーがメンバーのグループを取得
    my_group = Group.objects.filter(id__in=my_member)

    # グループに所属しているtripを取得
    trip_contents = Trip.objects.all().filter(group__in=my_group).values('id', 'trip_name', 'start', 'end')
    trips = Trip.objects.all().filter(group__in=my_group)
    for i in range(len(trip_contents)):
        spot = Spot.objects.filter(trip=trip_contents[i]['id'])
        if not spot:
            trips[i].delete()

    if my_group:
        all_group = my_group.values('id', 'title', 'user')
        # グループの作成者のusernameを取得
        group_owners = [CustomUser.objects.filter(id=all_group[i]['user']).values('username')[0]['username'] for i in range(len(all_group))]

    else:
        all_group = None
        group_owners = ''

    params = {
        'all_group': all_group,
        'group_owners': group_owners
    }

    return render(request, 'make_trip/groups.html', params)

# @login_required(login_url='/make_trip/')
def group_trip(request, num):
    # tripの情報があるかチェックする
    try:
        groups = Group.objects.get(id=num)
    except Group.DoesNotExist:
        raise Http404('このグループは存在しません')

    # グループ内の人数とグループの名前を取得
    member_cnt = Member.objects.filter(group=groups).count()
    group_name = Group.objects.filter(id=num).values('title')[0]['title']

    # request.userがグループのメンバーかどうかを判定
    member_exist = Member.objects.filter(group=num).filter(user=request.user)

    if member_exist:
        # DBにTripの情報が登録されている場合はそのデータを表示する
        if groups:
            # group = Group.objects.all().filter(user=request.user)
            # trip_obj = Trip.objects.filter(group__in=group)
            # print(group)
            trip_content_before = []
            trip_content_future = []
            trip_content = Trip.objects.all().filter(group=groups).values('id', 'trip_name', 'start', 'end')

            # print('trip_content:', trip_content)
            # 未来の旅行と過去の旅行に分ける
            for i in range(len(trip_content)):
                if trip_content[i]['end'] < datetime.date.today():
                    # 過去の旅行の場合はtrip_content_beforeに格納する
                    trip_content_before.append(trip_content[i])
                else:
                    # 未来の旅行の場合はtrip_content_futureに格納する
                    trip_content_future.append(trip_content[i])

        else:
            trip_content_before = []
            trip_content_future = []

        params = {
            'trip_content_future': trip_content_future,
            'trip_content_before': trip_content_before,
            'id': num,
            'member_cnt': member_cnt,
            'group_name': group_name
        }

        return render(request, 'make_trip/group_trip.html', params)
    else:
        return redirect(to='/make_trip/myPage')


# @login_required(login_url='/make_trip/')
def members(request, num):
    # 所属しているグループのtrip情報を取得

    # tripの情報があるかチェックする
    try:
        groups = Group.objects.get(id=num)
    except Group.DoesNotExist:
        raise Http404('このグループは存在しません')

    # request.userがグループのメンバーかどうかを判定
    member_exist = Member.objects.filter(group=num).filter(user=request.user)

    if member_exist:
        # グループ内の人数とグループの名前を取得
        members = Member.objects.filter(group=num).values('user', 'id')
        member_username = [CustomUser.objects.filter(id=members[i]['user']).values('username')[0]['username'] for i in range(len(members))]
        group_name = Group.objects.filter(id=num).values('title')[0]['title']

        # メンバー全員のIDを取得
        member_id = [members[i]['id'] for i in range(len(members))]

        params = {
            'ids': member_id,
            'members': member_username,
            'group_name': group_name
        }

        return render(request, 'make_trip/members.html', params)

    else:
        return redirect(to='/make_trip/myPage')

# @login_required(login_url='/make_trip/')
def member_delete(request, num):
    # request.userがグループのメンバーかどうかを判定
    member = Member.objects.filter(id=num).first()

    try:
        member = Member.objects.get(id=num)
    except Member.DoesNotExist:
        raise Http404('このメンバーは存在しません')

    request_member = Member.objects.filter(group=member.group.id).filter(user=request.user).first()

make_trip/templates/make_trip/add_group.html
<!DOCTYPE html>
{% extends 'make_trip/layout.html' %}
{% block container %}
{% load boost %}
<div class="container-fluid mt-5 pt-5">
    <div class="row justify-content-center d-flex">
        <div class="col-md-8 col-xl-6">
            <h3 class="text-secondary mb-5">参加するグループのURLを入力してください</h3>
            <form action="{% url 'make_trip:add_group' %}" method="post">
                <div class="row">
                    <div class="col-12 mb-5">
                        {% csrf_token %}
                        {{ input_url }}
                    </div>
                </div>
                <div class="col-6 col-md-4 col-xl-3 col-xs-12 mx-auto">
                    <button type="submit" class="btn btn-success btn-block">登録</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    $(function(){
        // aタグがクリックされた時に画面遷移させない
        $("#group_url").on('click', function(e){
            e.preventDefault();  // 画面遷移を無効化
        });
        /// コピーテキストボタンを実装
        $('a#group_url')
        // tooltip設定
        .tooltip({
            trigger: 'manual'
        })
        // tooltip表示後の動作を設定
        .on('shown.bs.tooltip', function(){
            setTimeout((function(){
            $(this).tooltip('hide');
            }).bind(this), 1500);
        })
        .on('click',function(){
            /// aタグのurlを取得
            let url = $('a#group_url').attr('href');

            // selectは直接できないから一旦textareaに入れる
            let textarea = $('<textarea></textarea>');
            textarea.text(url);
            $(this).append(textarea);
            textarea.select();
            // コピー結果を取得してtextareaは削除
            let copied = document.execCommand('copy');
            textarea.remove();
            // コピー結果によって表示変更
            if(copied){
                $('a#group_url').attr('data-original-title', 'コピーしました');
            }else{
                $('a#group_url').attr('data-original-title', 'コピー失敗しました');
            }
            // tooltip表示
            $(this).tooltip('show');
        });
    });
</script>
{% endblock %}

make_trip/templates/make_trip/add_member_complete.html
<!DOCTYPE html>
{% extends 'make_trip/layout.html' %}
{% block container %}
{% load boost %}
<div class="container-fluid pt-5">
    <div class="row justify-content-center d-flex mt-5">
        <div class="col-md-8 col-xl-6">
            <h2 class="text-secondary">『{{ group }}』に参加しますか？<br> </h2>
            <form action="{% url 'make_trip:add_member_complete' token %}" method="POST">
                {% csrf_token %}
                <!-- views側で参加ボタンを押したらmyPageに画面遷移するようにしておく -->
                <button type="submit" class="btn btn-success mt-5 mb-3 btn-lg">参加する</button>
                {% if messages %}
                    <ul class="messages list-unstyled">
                        {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }} text-danger"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

make_trip/templates/make_trip/create_this_group_trip.html
<!DOCTYPE html>
{% extends 'make_trip/layout.html' %}

{% block navigation %}
<ul class="navbar-nav mr-3 mt-2 mt-lg-0">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'make_trip:add_member' id %}">招待リンク</a>
    </li>
</ul>
<span class="h6 text-light mb-0 mr-3">グループ名:『{{ group_name }}』({{ member_cnt }}人)</span> <br>
{% endblock %}
{% block container %}
<div class="container-fluid mt-5">
    <div class="row justify-content-center d-flex">
        <div class="col-md-8 col-xl-6">
            <form action="{% url 'make_trip:create_this_group_trip' id %}" method="post">
                {% csrf_token %}
                <h4 class="text-secondary mb-2">旅行タイトルの作成</h4>
                    <div class="row p-3 justify-content-center">
                        <div class="col-8">
                            {{ trip.trip_name }}
                        </div>
                    </div>
                    <h4 class="text-secondary mt-5">旅行のスケジュール</h4>
                    <div class="row mt-3 justify-content-center">
                        <div class="col-5" id="start">
                            {{ trip.start }}
                            {% if error_msg_start %}
                                <ul class="list-unstyled">
                                    <li class="text-danger">{{ error_msg_start }}</li>
                                </ul>
                            {% endif %}
                        </div>
                        <p class="mt-2">〜</p>
                        <div class="col-5" id="end">
                            {{ trip.end }}
                            {% if error_msg_end %}
                                <ul class="list-unstyled">
                                    <li class="text-danger">{{ error_msg_end }}</li>
                                </ul>
                            {% endif %}
                        </div>
                    </div>
                    <h4 class="text-secondary mt-5">予算を入力してください</h4>
                    <div class="row justify-content-center mt-3">
                        <div class="col-10">
                            {{ budget.predict_money }}
                            {% if budget.predict_money.errors %}
                                <ul class="list-unstyled">
                                    {% for error in budget.predict_money.errors %}
                                        <li class="text-danger">{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-6 col-md-4 col-xl-3 col-xs-12 mx-auto mt-5">
                        <button type="submit" class="btn btn-success btn-block">登録</button>
                    </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    $(function(){
        $.datetimepicker.setLocale('ja');
        $('.bigDate').datetimepicker({
            timepicker: false,
            format: 'Y-m-d',
            numberOfMonths: 2
        });
        $('.smallDate').datetimepicker({
            step: 15,
            format: 'Y-m-d H:i',
        });
        let start, end;
        let now = new Date();
        // 今日の日付-1日しておくことでifが上手くいく
        now.setDate(now.getDate() - 1);
        console.log('now:', now);
        $('#start').find(".bigDate").on("blur", function () {
            let error = false;
            let value = $(this).val();
            // 今日の日付を取得する
            // フォームに入力された年月日のを入れる
            let year_ls = []
            let month_ls = []
            let day_ls = []

            // フォームに入力されたのはstringだから数字に直す
            for (let i=0; i<10; i++){
                if (i < 4){
                    year_ls += value[i];
                }else if(4 < i && i < 7){
                    month_ls += value[i];
                }else if(7 < i){
                    day_ls += value[i];
                }
            }
            // Dateの月は0~11になっている、日付は当日までをOKにしておくため
            start = new Date(Number(year_ls), Number(month_ls)-1, Number(day_ls));

            error = start.getTime() <= now;

            if (error) {
                //エラーで、エラーメッセージがなかったら
                if(!$(this).nextAll('span.error-info').length) {
                    //メッセージを後ろに追加
                    $(this).after('<span class = "error-info text-danger">' + now.getFullYear() + '年' + Number(now.getMonth() + 1) + '月' + Number(now.getDate() + 1) + '日' + '以降の日付を入力してください'+ '</span>');
                }
            }else{
                //エラーじゃないのにメッセージがあったら
                if($(this).nextAll('span.error-info').length) {
                    //消す
                    $(this).nextAll('span.error-info').remove();
                }
            }
            $('.bigDate').datetimepicker({
                defaultDate: start,
                timepicker: false,
                format: 'Y-m-d',
                numberOfMonths: 2
            });
        });
        $('#end').find(".bigDate").on("blur", function () {
            let error = false;
            let value = $(this).val();
            // 今日の日付を取得する
            // フォームに入力された年月日のを入れる
            let year_ls = []
            let month_ls = []
            let day_ls = []

            // フォームに入力されたのはstringだから数字に直す
            for (let i=0; i<10; i++){
                if (i < 4){
                    year_ls += value[i];
                }else if(4 < i && i < 7){
                    month_ls += value[i];
                }else if(7 < i){
                    day_ls += value[i];
                }
            }
            // Dateの月は0~11になっている、日付は当日までをOKにしておくため
            end = new Date(Number(year_ls), Number(month_ls)-1, Number(day_ls)+1);
            console.log('end:', end);

            if (end.getTime() <= start.getTime()){
                error = true;
            }

            if (error) {
                //エラーで、エラーメッセージがなかったら
                if(!$(this).nextAll('span.error-info').length) {
                    //メッセージを後ろに追加
                    $(this).after('<span class = "error-info text-danger">出発日以降の日付を入力してください'+ '</span>');
                }
            }else{
                //エラーじゃないのにメッセージがあったら
                if($(this).nextAll('span.error-info').length) {
                    //消す
                    $(this).nextAll('span.error-info').remove();
                }
            }
            $('.bigDate').datetimepicker({
                defaultDate: end,
                timepicker: false,
                format: 'Y-m-d',
                numberOfMonths: 2
            });
        });
        $('form').on('submit', function(e){
            if ($('span.error-info').length){
                console.log('エラーあり');
                e.preventDefault();
            }
        });
    });
</script>
{% endblock %}

make_trip/templates/make_trip/delete.html
<!DOCTYPE html>
{% extends 'make_trip/layout.html' %}

{% block container %}
<div class="container-fluid pt-5">
    <div class="row justify-content-center mt-5 d-flex">
        <div class="col-md-4">
            <div class="pb-5 mb-5">
                <div class="row justify-content-center">
                    <div class="col-12 m-3">
                        <form action="{% url 'make_trip:delete' id %}" method="post">
                            {% csrf_token %}
                            <a class="btn btn-light p-4" href="#" role="button">
                                {{ delete.trip_name }} <br>
                                {{ delete.start }} 〜 {{ delete.end }}
                            </a>
                            <br>
                            <button type="submit" class="btn btn-success mt-4 p-2">この旅行を削除する</button>
                            <!-- <button type="submit" class="btn btn-light btn-block border-0 m-3" style="background-color: rgba(191, 202, 63, 0.99);">この旅行を削除</button> -->
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
{% endblock %}

make_trip/templates/make_trip/group_trip.html
<!DOCTYPE html>
{% extends 'make_trip/layout.html' %}
{% block navigation %}
<ul class="navbar-nav mr-3 mt-2 mt-lg-0">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'make_trip:members' id %}">メンバーを表示</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'make_trip:create_this_group_trip' id %}">このグループで旅行作成</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'make_trip:add_member' id %}">招待リンク</a>
    </li>
</ul>
{% endblock %}

{% block container %}
    {% if not trip_content_future and not trip_content_before %}
        <div class="container-fluid pt-5">
            <div class="row justify-content-center d-flex mt-5">
                <div class="col-md-8 col-xl-6">
                    <h4 class="text-secondary mb-5">『{{ group_name }}』の旅行一覧(人数：{{ member_cnt }}人)</h4>
                    <h4 class="text-secondary">まだ、旅行は登録されていません...</h4>
                </div>
            </div>
        </div>
        {% else %}
        <div class="container-fluid">
            <div class="row justify-content-center mt-5 d-flex">
                <div class="col-md-8">
                    <div class="border-bottom border-dark pb-5 mb-5">
                        <h4 class="text-secondary mb-5">『{{ group_name }}』の旅行一覧(メンバー：{{ member_cnt }}人)</h4>
                        <h4 class="text-secondary">次の旅行</h4>
                        {% if trip_content_future %}
                            <div class="row justify-content-center">
                                {% for content in trip_content_future %}
                                    <div class="col-md-4 m-3 col-sm-4">
                                        <a class="btn btn-light pb-4 pt-4" href="{% url 'make_trip:trip' content.id %}" role="button">
                                            {{ content.trip_name }} <br>
                                            {{ content.start }} 〜 {{ content.end }}
                                        </a>
                                        <div class="row justify-content-end">
                                            <div class="col-sm-7 col-md-7 col-7 col-xl-4">
                                                <a class="text-success" href="{% url 'make_trip:trip' content.id %}"><i class="fa fa-edit"></i></a>
                                                <a class="ml-4 text-success" href="{% url 'make_trip:delete' content.id %}"><i class="fas fa-trash-alt"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                                {% endif %}
                            </div>
                            <h4 class="text-secondary">これまでの旅行</h4>
                            {% if trip_content_before %}
                            <div class="row justify-content-center">
                                {% for content in trip_content_before %}
                                <div class="col-4 m-3">
                                    <a class="btn btn-light btn-lg" href="{% url 'make_trip:trip' content.id %}" role="button">
                                        {{ content.trip_name }} <br>
                                        {{ content.start }} 〜 {{ content.end }}
                                    </a>
                                    <div class="row justify-content-end">
                                        <div class="col-sm-7 col-md-7 col-7 col-xl-4">
                                            <a class="text-success" href="{% url 'make_trip:trip' content.id %}"><i class="fa fa-edit"></i></a>
                                            <a class="ml-4 text-success" href="{% url 'make_trip:delete' content.id %}"><i class="fas fa-trash-alt"></i></a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

make_trip/templates/make_trip/logout.html
<!doctype html>
{% extends 'make_trip/layout.html' %}
{% block container%}
<div class="container-fluid pt-5">
    <div class="row">
        <div class="col-sm-12 mt-5 mb-4">
            <h3 class="text-light">ログアウトしますか？</h3>
        </div>
        <div class="col-12">
            <a name="logout" id="logout" class="btn btn-light" href="{% url 'account_logout' %}" role="button" style="color: rgba(130, 130, 130, 1);">ログアウト</a>
        </div>
    </div>
</div>
{% endblock %}